version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Stateless.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: pYU25F/E2Lsqt7XfWipKu3NlOjxphhNioNDtYqrYk0QvWwq21rohQp54BbhWx7+l
  on:
    branch: /^(master|dev)$/
